services:
  - type: web
    name: repo-markdown-crafter-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /status
    envVars:
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: "*"
      - key: NODE_VERSION
        value: 22.x 